apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lms-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: JWT_ALGORITHM
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: REDIS_URL
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: REDIS_PORT
        - name: USER_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: USER_SERVICE_URL
        - name: COURSE_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: COURSE_SERVICE_URL
        - name: ENROLLMENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: ENROLLMENT_SERVICE_URL
        - name: ASSESSMENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: ASSESSMENT_SERVICE_URL
        - name: PROGRESS_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: PROGRESS_SERVICE_URL
        - name: ANALYTICS_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: ANALYTICS_SERVICE_URL
        - name: COMMUNICATION_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: COMMUNICATION_SERVICE_URL
        - name: CONTENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: api-gateway-secrets
              key: CONTENT_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lms-staging
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
