apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: lms-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: DATABASE_URL
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: POSTGRES_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: JWT_ALGORITHM
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: REDIS_URL
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: lms-staging
spec:
  selector:
    app: course-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
