apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lms-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "staging"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lms-staging
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
