apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
  namespace: lms-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
      - name: progress-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-progress-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DATABASE_URL
          value: "postgresql://lms_staging_user:staging_password@postgres-service:5432/lms_staging_db"
        - name: POSTGRES_DB
          value: "lms_staging_db"
        - name: POSTGRES_USER
          value: "lms_staging_user"
        - name: POSTGRES_PASSWORD
          value: "staging_password"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: lms-staging
spec:
  selector:
    app: progress-service
  ports:
  - port: 8005
    targetPort: 8005
  type: ClusterIP
