apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: communication-service
        image: communication-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://postgres:postgres@postgres:5432/communication_db"