apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-analytics-service:latest
        ports:
        - containerPort: 8006
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: lms-production
spec:
  selector:
    app: analytics-service
  ports:
  - port: 8006
    targetPort: 8006
  type: ClusterIP
