apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: JWT_SECRET_KEY
          value: "production-super-secret-jwt-key-change-in-production"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: USER_SERVICE_URL
          value: "http://user-service:8001"
        - name: COURSE_SERVICE_URL
          value: "http://course-service:8002"
        - name: ENROLLMENT_SERVICE_URL
          value: "http://enrollment-service:8003"
        - name: ASSESSMENT_SERVICE_URL
          value: "http://assessment-service:8004"
        - name: PROGRESS_SERVICE_URL
          value: "http://progress-service:8005"
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:8006"
        - name: COMMUNICATION_SERVICE_URL
          value: "http://communication-service:8007"
        - name: CONTENT_SERVICE_URL
          value: "http://content-service:8008"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lms-production
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
