apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: communication-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-communication-service:latest
        ports:
        - containerPort: 8007
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: lms-production
spec:
  selector:
    app: communication-service
  ports:
  - port: 8007
    targetPort: 8007
  type: ClusterIP
