apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-content-service:latest
        ports:
        - containerPort: 8007
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: DATABASE_URL
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: POSTGRES_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: JWT_ALGORITHM
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: REDIS_URL
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: REDIS_PORT
        - name: UPLOAD_DIR
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: UPLOAD_DIR
        - name: MAX_FILE_SIZE
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: MAX_FILE_SIZE
        - name: ALLOWED_FILE_TYPES
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: ALLOWED_FILE_TYPES
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: lms-production
spec:
  selector:
    app: content-service
  ports:
  - port: 8007
    targetPort: 8007
  type: ClusterIP
