apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: lms-production
spec:
  selector:
    app: course-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
