apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: lms-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-user-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: lms-production
spec:
  selector:
    app: user-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
