apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
      - name: progress-service
        image: progress-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://postgres:postgres@postgres:5432/progress_db"