name: LMS Platform CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  AWS_REGION: eu-west-2
  ECR_REGISTRY: 436549840164.dkr.ecr.eu-west-2.amazonaws.com

jobs:
  # ============================================================================
  # TESTING JOB
  # ============================================================================
  test:
    name: Test Backend Services
    runs-on: ubuntu-latest
    continue-on-error: true
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    strategy:
      matrix:
        service: [user_service, course_service, enrollment_service, assessment_service, progress_service, analytics_service, communication_service, content_service, api_gateway]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend/${{ matrix.service }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx

    - name: Run tests
      run: |
        cd backend/${{ matrix.service }}
        python -m pytest tests/ -v --cov=app --cov-report=xml || echo "Tests failed but continuing..."

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./backend/${{ matrix.service }}/coverage.xml
        flags: ${{ matrix.service }}
        name: ${{ matrix.service }}-coverage

  # ============================================================================
  # FRONTEND TESTING
  # ============================================================================
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run tests
      run: |
        cd frontend
        npm run test:ci || echo "Frontend tests failed but continuing..."

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage

  # ============================================================================
  # SECURITY SCANNING
  # ============================================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # ============================================================================
  # BUILD IMAGES
  # ============================================================================
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [test, test-frontend, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::436549840164:role/github_action_role
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.ECR_REGISTRY }}/lms-api-gateway
          ${{ env.ECR_REGISTRY }}/lms-user-service
          ${{ env.ECR_REGISTRY }}/lms-course-service
          ${{ env.ECR_REGISTRY }}/lms-enrollment-service
          ${{ env.ECR_REGISTRY }}/lms-assessment-service
          ${{ env.ECR_REGISTRY }}/lms-progress-service
          ${{ env.ECR_REGISTRY }}/lms-analytics-service
          ${{ env.ECR_REGISTRY }}/lms-communication-service
          ${{ env.ECR_REGISTRY }}/lms-content-service
          ${{ env.ECR_REGISTRY }}/lms-frontend

    - name: Build and push API Gateway
      uses: docker/build-push-action@v5
      with:
        context: ./backend/api_gateway
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-api-gateway:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push User Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/user_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-user-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Course Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/course_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-course-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Enrollment Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/enrollment_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-enrollment-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Assessment Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/assessment_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-assessment-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Progress Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/progress_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-progress-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Analytics Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/analytics_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-analytics-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Communication Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/communication_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-communication-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Content Service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/content_service
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-content-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.ECR_REGISTRY }}/lms-frontend:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

  # ============================================================================
  # DEPLOY TO STAGING
  # ============================================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    environment: staging
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::436549840164:role/github_action_role
        aws-region: eu-west-2

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        
        # Test kubectl connection
        kubectl cluster-info
        
        # Create namespace if it doesn't exist
        kubectl create namespace lms-staging --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to staging
      run: |
        # Update image tags in Kubernetes manifests
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-user-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-user-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-enrollment-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-enrollment-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-assessment-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-assessment-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-progress-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-progress-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-analytics-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-analytics-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-communication-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-communication-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-content-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-content-service:${{ github.sha }}|g' k8s/staging/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-frontend:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-frontend:${{ github.sha }}|g' k8s/staging/*.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/staging/ --validate=false
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/api-gateway -n lms-staging --timeout=300s
        kubectl rollout status deployment/user-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/course-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/enrollment-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/assessment-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/progress-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/analytics-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/communication-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/content-service -n lms-staging --timeout=300s
        kubectl rollout status deployment/frontend -n lms-staging --timeout=300s

    - name: Run smoke tests
      run: |
        # Wait for services to be ready
        sleep 60
        
        # Test API Gateway
        curl -f http://staging-api.lms.com/health || exit 1
        
        # Test frontend
        curl -f http://staging.lms.com/ || exit 1

  # ============================================================================
  # DEPLOY TO PRODUCTION
  # ============================================================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: production
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::436549840164:role/github_action_role
        aws-region: eu-west-2

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        
        # Test kubectl connection
        kubectl cluster-info
        
        # Create namespace if it doesn't exist
        kubectl create namespace lms-production --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to production
      run: |
        # Update image tags in Kubernetes manifests
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-api-gateway:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-user-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-user-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-course-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-enrollment-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-enrollment-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-assessment-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-assessment-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-progress-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-progress-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-analytics-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-analytics-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-communication-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-communication-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-content-service:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-content-service:${{ github.sha }}|g' k8s/production/*.yaml
        sed -i 's|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-frontend:.*|436549840164.dkr.ecr.eu-west-2.amazonaws.com/lms-frontend:${{ github.sha }}|g' k8s/production/*.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/production/ --validate=false
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/api-gateway -n lms-production --timeout=300s
        kubectl rollout status deployment/user-service -n lms-production --timeout=300s
        kubectl rollout status deployment/course-service -n lms-production --timeout=300s
        kubectl rollout status deployment/enrollment-service -n lms-production --timeout=300s
        kubectl rollout status deployment/assessment-service -n lms-production --timeout=300s
        kubectl rollout status deployment/progress-service -n lms-production --timeout=300s
        kubectl rollout status deployment/analytics-service -n lms-production --timeout=300s
        kubectl rollout status deployment/communication-service -n lms-production --timeout=300s
        kubectl rollout status deployment/content-service -n lms-production --timeout=300s
        kubectl rollout status deployment/frontend -n lms-production --timeout=300s

    - name: Run smoke tests
      run: |
        # Wait for services to be ready
        sleep 60
        
        # Test API Gateway
        curl -f https://api.lms.com/health || exit 1
        
        # Test frontend
        curl -f https://lms.com/ || exit 1

    - name: Notify deployment
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() && github.event_name == 'push' 